# [START cloudbuild_npm_node]
steps:
# Install dependencies
  - name: node
    entrypoint: npm
    args: ['install']
  # Run tests
  - name: node
    entrypoint: npm
    args: ['test']
  # Run custom commands
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  # [END cloudbuild_npm_node]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'suchita2007/node-js:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$NAME --password=$$PASS']
    secretEnv: ['NAME', 'PASS']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'suchita2007/node-js:$SHORT_SHA']
  #this is test repo
  #This is main branch
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-vatan-public'
  #step 4
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
     'set', 
     'image', 
     'deployment', 
     'my-source-repo-suchita', 
     'my-source-repo-suchita=suchita2007/node-js:$SHORT_SHA'
    ]
    env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-vatan-public'
availableSecrets:
    secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SECRET-A/versions/latest
      env: 'PASS'
    - versionName: projects/$PROJECT_ID/secrets/SECRET-B/versions/latest
      env: 'NAME'
images: 
  - 'suchita2007/node-js:$SHORT_SHA'
