apiVersion: v1
kind: Pod
metadata:
  name: my-source-repo-suchita
spec:
  containers:
  - name: my-source-repo-suchita
    image: suchita2007/node-js:$SHORT_SHA
    ports:
    - containerPort: 3000    
  imagePullSecrets:
  - name: regcred
  
